### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by erss** [jmarkow/zftftb#7]
Once you make the template, I'm not sure how to perform the manual cluster cut in step 5.  Instead of running through the other .wav files in the sound folder, it runs through my other MATLAB script files.

**Comment by jmarkow** [comment]
This isn't entirely clear in the documentation, but the data is assumed to be in the directory you're currently in.  Navigate to the folder with the .wav files then try re-running the code.  I'll add this to the documentation.  Let me know if you're still having trouble.

**Comment by erss** [comment]
Ok, do you mean save the new directory in the same file with all the other .wav files?

**Comment by jmarkow** [comment]
That's right.  `cd` into the directory with the .wav files and _then_ run `zftftb_song_clust`.
